"""Core data-cleaning functions, available as ``fda_toolkit.core``."""

from fda_toolkit.core.columns import (
    classify_columns,
    clean_column_headers,
    combine_columns,
    drop_constant_columns,
    drop_empty_columns,
    drop_sparse_columns,
    make_unique_columns,
    rename_columns,
    reorder_columns,
    select_columns,
    select_columns_by_type,
    split_column,
)
from fda_toolkit.core.duplicates import (
    deduplicate_by_priority,
    find_duplicates,
    remove_duplicates,
)
from fda_toolkit.core.missing import coerce_empty_to_nan, fill_missing
from fda_toolkit.core.outliers import (
    cap_outliers,
    detect_outliers_iqr,
    flag_outliers,
    remove_outliers_iqr,
    remove_outliers_zscore,
    winsorize_outliers,
)
from fda_toolkit.core.rows import (
    drop_empty_rows,
    drop_missing_required,
    drop_sparse_rows,
    filter_by_date_range,
    filter_by_value_range,
    filter_rows,
    remove_repeated_headers,
    remove_summary_rows,
    trim_leading_trailing_rows,
)
from fda_toolkit.core.text import (
    clean_categorical_column,
    clean_text_column,
    standardize_text_values,
)
from fda_toolkit.core.types import (
    clean_boolean_column,
    clean_date_column,
    clean_numeric_column,
    convert_data_types,
    convert_date_columns,
)

__all__ = [
    "cap_outliers",
    "classify_columns",
    "clean_boolean_column",
    "clean_categorical_column",
    "clean_column_headers",
    "clean_date_column",
    "clean_numeric_column",
    "clean_text_column",
    "coerce_empty_to_nan",
    "combine_columns",
    "convert_data_types",
    "convert_date_columns",
    "deduplicate_by_priority",
    "detect_outliers_iqr",
    "drop_constant_columns",
    "drop_empty_columns",
    "drop_empty_rows",
    "drop_missing_required",
    "drop_sparse_columns",
    "drop_sparse_rows",
    "fill_missing",
    "filter_by_date_range",
    "filter_by_value_range",
    "filter_rows",
    "find_duplicates",
    "flag_outliers",
    "make_unique_columns",
    "remove_duplicates",
    "remove_outliers_iqr",
    "remove_outliers_zscore",
    "remove_repeated_headers",
    "remove_summary_rows",
    "rename_columns",
    "reorder_columns",
    "select_columns",
    "select_columns_by_type",
    "split_column",
    "standardize_text_values",
    "trim_leading_trailing_rows",
    "winsorize_outliers",
]
